# Generated by Django 4.2 on 2023-04-22 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('contents', models.TextField(blank=True)),
                ('last_updated', models.PositiveBigIntegerField()),
            ],
        ),
    ]
